---
- name: installation serveur web
  hosts: 
    ansible_host: "{{ ip }}"
  remote_user: root
  
  tasks:
    - name: install apache
      apt: name=apache2
    - name: install php
      apt: name=php
