---
- name: installation serveur web
  hosts: all
  become: yes
  
  tasks:
    - name: install apache
      apt: name=apache2
    - name: install php
      apt: name=php
    - name: install php2
      apt: name=libapache2-mod-php
      
    - name: virtualhost
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
      
    - name: a2ensite
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify: relancer Apache
      
    - name: phpinfo
      copy: src=index.php dest=/var/www/html/ mode=0644
      
    - name: remove default index.html
      file:
        path: /var/www/html/index.html
        state: absent
      
  handlers:
    - name: relancer Apache
      service: name=apache2 state=reloaded
