---
- name: installation serveur web
  hosts: all
  become: yes
  
  tasks:
    - name: install apache
      apt: name=apache2
    - name: install php
      apt: name=php
    - name: install lib apache2 mod php
      apt: name=libapache2-mod-php
      
    - name: virtualhost
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
      
    - name: a2ensite
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify: relancer Apache
      
    - name: phpinfo
      copy: src=index.php dest=/var/www/html/ mode=0644
      
    - name: remove default index.html
      file:
        path: /var/www/html/index.html
        state: absent
      
  handlers:
    - name: relancer Apache
      service: name=apache2 state=reloaded
# Ce playbook installe un serveur web avec php sur l'hôte.
# Pour ce faire il va :
# - Installer le serveur web Apache 2 et installer et configurer PHP.
# - Importer et installer le fichier de configuration de l'hôte viratuel apache.
# - Modifier le fichier index par défaut en fichier phpinfo permettant de vérifier le bonfonctionnement de PHP.
# - Relancer le service apache2 afin d'appliquer les modifications.
