- name: Copy a "sudoers" file on the remote machine for editing
  hosts: all
  become: yes
  copy:
    src: /etc/sudoers
    dest: /etc/sudoers.edit
    remote_src: yes
    validate: /usr/sbin/visudo -cf %s
