---
- hosts: all

  tasks:
  - name: Copy file with owner and permission, using symbolic representation
    become: yes
    ansible.builtin.copy:
      src: "{{ source }}"
      dest: "{{ destination }}#
      owner: foo
      group: foo
      mode: u=rw,g=r,o=r
