  - hosts: all
    become: yes
    tasks:
      - name: Synchronize directories on remote host.
        ansible.posix.synchronize:
          src: "{{ Source }}"
          dest: rsync://somehost.com/"{{ destination }}"
          checksum: yes
          times: no
