  - hosts: all
    become: yes
    tasks:
      - name: installation de rsync
        apt: apt: name=rsync update_cache=yes state=latest
      - synchronize:
          src: "{{path}}"
          dest: rsync://192.168.121.90/"{{destination}}"
