---
- hosts: all
  tasks:
  - name: Create backup archive
    command: tar -czf {{ansible_hostname}}_{{ansible_date_time.epoch}}_{{archive_name}}.tgz {{files_path}}
  - name: Upload backup archive to server
    command: scp {{ansible_hostname}}_{{ansible_date_time.epoch}}_{{archive_name}}.tgz user@192.168.1.146:/home/user/backup
  - name: Delete local backup archive
    file:
      path: "{{ansible_hostname}}_{{ansible_date_time.epoch}}_{{archive_name}}.tgz"
      state: absent
# Ce playbook fait une sauvegarde d'un repertoire d'un hote sur le serveur.
# Le répértoire de sauvegarde et le nom de sauvegarde sont définis par l'utilisateur.
# Pour ce faire il va :
# - Créer une archive en tarball des fichier à sauvegarder avec un nom permetant d'etablir des versions.
# - Déplacer cette archive en SCP sur le serveur.
# - Supprimer sur l'hote local l'archive de sauvegarde
