---
- hosts: all
  become: yes
  tasks:
  - name: Import backup archive to host
    command: scp user@192.168.1.146:/home/user/backup/{{archive_name}} /
  - name: Extract backup archive
    command: tar -xzf /{{archive_name}}
  - name: Delete local backup archive
    file:
      path: "/{{archive_name}}"
      state: absent
