  - hosts: all
    become: yes
    tasks:
    - name: installation de rsync
      apt: name=rsync update_cache=yes state=latest
    - synchronize:
        mode: pull
        src: "{{source}}"
        dest: "{{destination}}"
