---
- hosts: all
  tasks:
  - name: compress directory from "{{ source }}" to "{{ destination }}".tgz
    become: yes
    community.general.archive:
      path: /path/to/foo
      dest: /path/to/foo.tgz
