---
- hosts: all
  tasks:
  - name: compress directory from "{{ source }}" to "{{ destination }}".tgz
    become: yes
    community.general.archive:
      path: "{{ soucre }}"
      dest: "{{ destination }}".tgz
