---
- hosts: all

  tasks:
  - name: Installing libvirt
    become: yes
    apt: name=qemu-kvm update_cache=yes state=latest
    apt: name=libvirt-daemon-system update_cache=yes state=latest
    apt: name=libvirt-clients update_cache=yes state=latest
    apt: name=bridge-utils update_cache=yes state=latest
    apt: name=virtinst update_cache=yes state=latest
    apt: name=virt-manager update_cache=yes state=latest
  
  - name: Installing Vagrant
    become: yes
    apt: name=vagrant update_cache=yes state=latest
  
  - name: Creates directory
    file:
      path: "{{path}}"
      state: directory

  - name: Ansible create file with content example
    copy:
      dest: "{{path}}/Vagrantfile"
      content: |
        Vagrant.configure("2") do |config|
          config.vm.box = "debian/buster64"

         config.vm.provider "libvirt" do |vb|
            vb.memory = "{{ram}}"
            vb.cpus = "{{cpu}}"
          end
            config.vm.define "{{ nom_vm }}" do |b|
              b.vm.hostname = "{{ nom_vm }}"
              b.vm.network :private_network, :ip => "{{ip_address}}"
            end
        end
        
  - name: Run vagrant up
    command: vagrant up
    args:
      chdir: "{{path}}"
# Ce playbook permet de créer un machine virtuelle sur un hôte.
# La configuration de cette VM est définie par l'utilisateur (Répértoire d'installation, nom, nombre de coeur CPU, taille de la RAM, adresse IP).
# Pour ce faire il va :
# - Installer Libvirt et Vagrant si il ne sont pas déjà installés.
# - créer le répertoire d'installation.
# - écrire le Vagrantfile de la machine avec la configuration définie par l'utilisateur.
# - Démarrer la machine
