---
- hosts: all
  tasks:
  - name: Installing libvirt
    apt: name=qemu-kvm update_cache=yes state=latest
    apt: name=libvirt-daemon-system update_cache=yes state=latest
    apt: name=libvirt-clients update_cache=yes state=latest
    apt: name=bridge-utils update_cache=yes state=latest
    apt: name=virtinst update_cache=yes state=latest
    apt: name=virt-manager update_cache=yes state=latest
  
  - name: Installing Vagrant
    apt: name=vagrant update_cache=yes state=latest
  
  - name: Creates directory
    file:
      path: "{{path}}"
      state: directory

  - name: Ansible create file with content example
    copy:
      dest: "{{path}}/Vagrantfile"
      content: |
        Vagrant.configure("2") do |config|
          config.vm.box = "debian/jessie64"
         config.vm.provider "libvirt" do |vb|
            vb.memory = "{{ram}}"
            vb.cpus = "{{cpu}}"
          end
           config.vm.provision "ansible" do |ansible|
             ansible.playbook = "ispmail.yml"
             ansible.sudo = true
          end
          
            config.vm.define "mail" do |b|
              b.vm.hostname = "mail"
              b.vm.network :private_network, :ip => "{{ip_address}}"
            end
        end
        
  - name: Run vagrant up
    command: vagrant up
    args:
      chdir: "{{path}}"
