# manager

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

  # manager
  config.vm.define "manager" do |b|
    b.vm.box = "boxomatic/debian-11"
    b.vm.hostname = "manager"
    b.vm.network "private_network", ip: "10.0.0.2"
    b.vm.network "forwarded_port", guest: 80, host: 8080

    b.vm.provision "shell", inline: <<-SHELL
	sudo cp /vagrant/manager/hosts /etc/

	sudo useradd -m manager-ansible -G sudo -s /bin/bash
	echo "manager-ansible:root" | sudo chpasswd

	sudo -u manager-ansible mkdir /home/manager-ansible/.ssh/
	sudo -u manager-ansible ssh-keygen -N root -f /home/manager-ansible/.ssh/cle_ansible
	sudo cp /home/manager-ansible/.ssh/cle_ansible.pub /vagrant/
    SHELL

    b.vm.provision "shell", path: "provision.sh", args: "manager"
  end
end

# node

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

  config.vm.define "node" do |b|
    b.vm.box = "boxomatic/debian-11"
    b.vm.hostname = "node"
    b.vm.network "private_network", ip: "10.0.0.3"

    b.vm.provision "shell", inline: <<-SHELL
        sudo useradd -m node-ansible -G sudo -s /bin/bash
        echo "node-ansible:root" | sudo chpasswd

        sudo -u node-ansible mkdir /home/node-ansible/.ssh/
	sudo cp /vagrant/cle_ansible.pub /home/node-ansible/.ssh/
	sudo -u node-ansible cat /home/node-ansible/.ssh/cle_ansible.pub >> /home/node-ansible/.ssh/authorized_keys
	sudo rm /home/node-ansible/.ssh/cle_ansible.pub /vagrant/cle_ansible.pub
    SHELL

    b.vm.provision "shell", path: "provision.sh", args: "node"
  end
end

# vim: ft=ruby syn=ruby fileencoding=utf-8 sw=2 ts=2 ai eol et si
