---
- name: installation serveur FTP
  hosts: all
  become: yes
  
  tasks:
    - name: install ProFTPd
      apt: name=proftpd
    
      
    - name: Configure ProFTPd
      template: src=proftpd.conf dest=/etc/proftpd/proftpd.conf
      
  handlers:
    - name: relancer ProFTPd
      service: name=proftpd state=reloaded
