---
- name: installation serveur bdd
  hosts: all
  become: yes

  tasks:
    - name: install mariadb
      apt:
        name:
          - mariadb-server
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: copy fichier requete
      copy: src=requete.sql dest=/tmp/requete.sql
    - name: requete sql
      command: mysql < /tmp/requete.sql


        
  
# Ce playbook va installer un SGBD et PhpMyAdmin sur la machine hôte.
# Pour ce faire il va :
# - Installer mariaDB, PIP & php
# - Active le serveur mariaDB dans la liste des services
# - Installer et configurer les modules php ncessaire à la mise en service de PhpMyAdmin
# - Installer phpMyAdmin
