---
  - hosts: all
    become: true
    tasks:
      - name: install mysql
        apt: name=mysql-server update_cache=yes state=latest
      - name: start up the mysql service  
        ansible.builtin.shell: "systemctl start mysql"  
      - name: ensure mysql is enabled to run on startup  
        ansible.builtin.service: 
          name: mysql 
          state: started 
          enabled: yes
