---
  - hosts: all
    become: true
    tasks:
      - name: install mariadb
        apt: name=mariadb-server update_cache=yes state=latest
      - name: start up the mariadb service  
        ansible.builtin.shell: "systemctl start mariadb"  
      - name: ensure mariadb is enabled to run on startup  
        ansible.builtin.service: 
          name: mariadb 
          state: started 
          enabled: yes
