---
- name: installation serveur bdd
  hosts: all
  become: yes
  
  tasks: 
    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'python3-pymysql', 'php', 'php-mysql' ]
    - name: Download mysql
      get_url:
        url: https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb
        dest: /tmp/mysql.deb
    - name:  install mysql
      command: apt install /tmp/mysql.deb -f -y
    - name: start up the mysql service 
      command: systemctl enable --now mysql.service


        
  
# Ce playbook va installer un SGBD et PhpMyAdmin sur la machine hôte.
# Pour ce faire il va :
# - Installer mariaDB, PIP & php
# - Active le serveur mariaDB dans la liste des services
# - Installer et configurer les modules php ncessaire à la mise en service de PhpMyAdmin
# - Installer phpMyAdmin
