---
  - hosts: all
    become: true
    tasks:
      apt: 
      name=mariadb-server update_cache=yes state=latest
      name=python3-pymysql update_cache=yes state=latest
      name=php update_cache=yes state=latest
      - name: start up the mariadb service 
        ansible.builtin.shell: "systemctl start mariadb"  
      - name: ensure mariadb is enabled to run on startup  
        ansible.builtin.service: 
          name: mariadb 
          state: started 
          enabled: yes
      - name: Set the root password
        mysql_user:
          name: root
          password: azerty
          login_unix_socket: /var/run/mysqld/mysqld.sock
