---
  - hosts: all
    become: true
    tasks:
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mysql-server', 'python3-pymysql', 'php', 'php-mysql' ]
      - name: start up the mariadb service  
        ansible.builtin.shell: "systemctl start mariadb"  
      - name: ensure mariadb is enabled to run on startup  
        ansible.builtin.service: 
          name: mariadb 
          state: started 
          enabled: yes
      - name: Set the root password
        mysql_user:
          name: root
          password: azerty
          login_unix_socket: /var/run/mysqld/mysqld.sock
