---
- name: installation serveur bdd
  hosts: all
  become: yes

  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost
    - name: remove remote root
      mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent


        
  
# Ce playbook va installer un SGBD et PhpMyAdmin sur la machine hôte.
# Pour ce faire il va :
# - Installer mariaDB, PIP & php
# - Active le serveur mariaDB dans la liste des services
# - Installer et configurer les modules php ncessaire à la mise en service de PhpMyAdmin
# - Installer phpMyAdmin
