---
- hosts: all
  tasks:
  - name: Add user ansible-user
    user:
      name: ansible-user
      group: sudo
      append: yes
      state: present
      create_home: no
      uid: 666
      shell: /usr/sbin/nologin
      system: yes
