---
- name: installation serveur bdd
  hosts: all
  become: yes
  
  tasks:
    -name: install mariadb-server
    apt: mariadb-server
    -name: start up mariadb service
    ansible.builtin.shell: "systemctl start mariadb"
    - name: ensure mariadb is enabled to run on startup  
      ansible.builtin.service: 
      name: mariadb 
        state: started 
        enabled: yes
