---
- name: installation bdd
  hosts: all
  become: yes
  
  tasks:
    - name: install apache
      apt: name=mariadb-server
    - name: install php
      apt: name=php
    -name: start up mariadb service
    ansible.builtin.shell: "systemctl start mariadb"
    - name: ensure mariadb is enabled to run on startup  
      ansible.builtin.service: 
      name: mariadb 
        state: started 
        enabled: yes
