---
- hosts: all
  become: yes
  
  tasks:
    - name: install apache
      apt: name=mariadb-server
    - name: install php
      apt: name=php
    - name: start up mariadb service
      ansible.builtin.shell: "systemctl start mariadb"

