---
- hosts: all
  become: yes
  
  tasks:
    - name: install apache
      apt: name=mariadb-server
    - name: install php
      apt: name=php
    - name: install python3-pymysql
      apt: name=python3-pymysql
    - name: start up mariadb service
      ansible.builtin.shell: "systemctl start mariadb"
    - name: ensure mariadb is enabled to run on startup  
      ansible.builtin.service:
        name: mariadb
        enabled: yes
    - name: Set the root password
      mysql_user:
        name: root
        password: azerty
        login_unix_socket: /var/run/mysqld/mysqld.sock   
    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
