- name: Install vagrant
  hosts: all
  become: yes
  remote_user: vagrant

  tasks:
  - name: Installing curl
    apt:
      name: curl
      state: latest
      update_cache: yes

  - name: Download Vagrant GPG
    get_url:
      url: https://apt.releases.hashicorp.com/gpg
      dest: /tmp/vagrant.gpg
